### ISSUE TITLE
[pydantic] `v2` Breaking changes

### ISSUE THREAD

**Issue by NiceAesth** [NiceAesth/aiosu#149]
Pydantic `v2` has recently been released, and introduces many breaking changes. Since this library is one that the user might potentially be using in their own project as well, I am unsure about how to proceed regarding whether to migrate to `v2` yet or not. Would appreciate some thoughts on this.

Migration would result in significant performance improvements, at the cost of requiring people to migrate their own projects to pydantic `v2` if they are also using the library (or at least change imports to `pydantic.v1` as the library still provides those)

If I proceed with migration, relevant libraries such as `aiordr` will also be migrated to `v2` alongside everything else.

Relevant: https://docs.pydantic.dev/latest/migration/

**Comment by NiceAesth** [comment]
CC'ing major users of the library: @7mochi @mayacopeland @cmyui @tsunyoku @aticie @tobycm

**Comment by cmyui** [comment]
LGTM also most of the backwards incompatibilities i've run into from this upgrade are related to more complex feature use (e.g. generic models) which most users probably won't run into

**Comment by NiceAesth** [comment]
> LGTM also most of the backwards incompatibilities i've run into from this upgrade are related to more complex feature use (e.g. generic models) which most users probably won't run into

I was a bit upset at the removal of parse_raw and parse_file, but I guess I will simply reimplement them as they were quite useful with how the library was structured

**Comment by NiceAesth** [comment]
Thanks for the feedback, I will start work on a separate `v2` branch for now.

**Comment by tobycm** [comment]
nice
